server:
  port: 5000

spring:
  application:
    name: consume-user #注册到eureka服务器的名字

eureka:
  client:
    service-url:
      #eureka服务器提供的注册地址，配置的eureka服务路径
      defaultZone: http://eureka:3000/eureka,http://eureka1:3001/eureka,http://eureka2:3002/eureka
  instance:
    instance-id: user-1 #注册到eureka服务器的唯一实例id
    prefer-ip-address: true #是否显示ip地址
    #客户端向服务器发送心跳的间隔时间，默认30s
    lease-renewal-interval-in-seconds: 10
    #eureka服务器收到实例最后一次发送的心跳后，删除实例的等待时间，默认90s
    lease-expiration-duration-in-seconds: 30

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000 #设置超时时长
      circuitBreaker:
        requestVolumeThreshold: 5   #  10秒种访问5次都失败的话, 会断开服务,不调用方法,直接进入fallback
        sleepWindowInMilliseconds : 5000   #默认是5秒 5秒后尝试再访问一次服务器
  threadpool:
    default:
      coreSize: 10

feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
